### ISSUE TITLE
Feature Request: matrix() function to have a rotation argument

### ISSUE THREAD

**Issue by armando-fandango** [ResidentMario/missingno#118] opened 2020-07-26 15:31 UTC
Sometimes we may not want the X labels to be rotated by 45, hence I propose that we make it an argument and set default value to 45. If you like the idea, you can assign to me and I will be happy to code and test and send PR.

**Comment by ResidentMario** [comment] 2022-02-20 00:33
Dupe of #112, feature added in #153.

**Closed by ResidentMario** 2022-02-20 00:33 UTC
Labels: feature request
