### ISSUE TITLE
No way to extract values from matplotlib charts

### ISSUE THREAD

**Issue by lodowner** [ResidentMario/missingno#109] opened 2020-06-21 20:58 UTC
I saw the issue here https://github.com/ResidentMario/missingno/issues/86 however it would be really useful if it were possible to extract the following from bar() or matrix():

a) A df or array of the names of all the columns with missing data from 
b) A df or array of the % of data completness as show on y-axis of bar()

Is it possible to do this on a columnar basis as opposed to a row basis?
I attempted this using various matplotlib methods but to no avail.

**Comment by lodowner** [comment] 2020-06-21 21:25
That said, this could of course be achieved using;

`df.isnull().sum().sort_values(ascending = False)`

**Comment by ResidentMario** [comment] 2020-06-21 21:31
Yes exactly. Dupe of #108.

**Closed by ResidentMario** 2020-06-21 21:31 UTC
