### ISSUE TITLE
TypeError 

### ISSUE THREAD

**Issue by gkirlik** [ResidentMario/missingno#35] opened 2017-07-17 15:10 UTC
Hello,

**missingno.bar**  is generating type error. I tried to run for different data frames. It created same error. How can I resolve the problem?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-54-d6279afe6478> in <module>()
----> 1 msno.bar(df.sample(10))

/usr/local/lib/python3.5/dist-packages/missingno/missingno.py in bar(df, figsize, fontsize, labels, log, color, inline, filter, n, p, sort)
    347     # Create the basic plot.
    348     fig = plt.figure(figsize=figsize)
--> 349     (nullity_counts / len(df)).plot(kind='bar', figsize=figsize, fontsize=fontsize, color=color, log=log)
    350 
    351     # Get current axis.

/usr/local/lib/python3.5/dist-packages/pandas/plotting/_core.py in __call__(self, kind, ax, figsize, use_index, title, grid, legend, style, logx, logy, loglog, xticks, yticks, xlim, ylim, rot, fontsize, colormap, table, yerr, xerr, label, secondary_y, **kwds)
   2441                            colormap=colormap, table=table, yerr=yerr,
   2442                            xerr=xerr, label=label, secondary_y=secondary_y,
-> 2443                            **kwds)
   2444     __call__.__doc__ = plot_series.__doc__
   2445 

/usr/local/lib/python3.5/dist-packages/pandas/plotting/_core.py in plot_series(data, kind, ax, figsize, use_index, title, grid, legend, style, logx, logy, loglog, xticks, yticks, xlim, ylim, rot, fontsize, colormap, table, yerr, xerr, label, secondary_y, **kwds)
   1882                  yerr=yerr, xerr=xerr,
   1883                  label=label, secondary_y=secondary_y,
-> 1884                  **kwds)
   1885 
   1886 

/usr/local/lib/python3.5/dist-packages/pandas/plotting/_core.py in _plot(data, x, y, subplots, ax, kind, **kwds)
   1682         plot_obj = klass(data, subplots=subplots, ax=ax, kind=kind, **kwds)
   1683 
-> 1684     plot_obj.generate()
   1685     plot_obj.draw()
   1686     return plot_obj.result

/usr/local/lib/python3.5/dist-packages/pandas/plotting/_core.py in generate(self)
    238         self._compute_plot_data()
    239         self._setup_subplots()
--> 240         self._make_plot()
    241         self._add_table()
    242         self._make_legend()

/usr/local/lib/python3.5/dist-packages/pandas/plotting/_core.py in _make_plot(self)
   1211                 rect = self._plot(ax, self.ax_pos + (i + 0.5) * w, y, w,
   1212                                   start=start, label=label,
-> 1213                                   log=self.log, **kwds)
   1214             self._add_legend_handle(rect, label, index=i)
   1215 

/usr/local/lib/python3.5/dist-packages/pandas/plotting/_core.py in _plot(cls, ax, x, y, w, start, log, **kwds)
   1158     @classmethod
   1159     def _plot(cls, ax, x, y, w, start=0, log=False, **kwds):
-> 1160         return ax.bar(x, y, w, bottom=start, log=log, **kwds)
   1161 
   1162     @property

/usr/local/lib/python3.5/dist-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1896                     warnings.warn(msg % (label_namer, func.__name__),
   1897                                   RuntimeWarning, stacklevel=2)
-> 1898             return func(ax, *args, **kwargs)
   1899         pre_doc = inner.__doc__
   1900         if pre_doc is None:

/usr/local/lib/python3.5/dist-packages/matplotlib/axes/_axes.py in bar(self, left, height, width, bottom, **kwargs)
   2056             linewidth *= nbars
   2057 
-> 2058         color = list(mcolors.to_rgba_array(color))
   2059         if len(color) == 0:  # until to_rgba_array is changed
   2060             color = [[0, 0, 0, 0]]

/usr/local/lib/python3.5/dist-packages/matplotlib/colors.py in to_rgba_array(c, alpha)
    235         return result
    236     # Convert one at a time.
--> 237     result = np.empty((len(c), 4), float)
    238     for i, cc in enumerate(c):
    239         result[i] = to_rgba(cc, alpha)

TypeError: object of type 'float' has no len()

**Comment by ResidentMario** [comment] 2017-07-17 15:52
Dupe of #34.

This is an issue in `pandas` that apparently got fixed in `20.3`. So the remedy is to update your version of `pandas` to the latest one.

**Closed** 2017-07-17 15:56 UTC
